[build]
  command = "npm run build"
  publish = "dist"
  node_version = "20"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Redirect to remove trailing slashes
[[redirects]]
  from = "/*/"
  to = "/:splat"
  status = 301
  force = true

# Handle 404s
[[redirects]]
  from = "/*"
  to = "/404"
  status = 404

# Asset caching
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
