name: Health Check

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Biome action
        uses: ./.github/actions/biome
